<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/grpc/cart.proto

namespace GPBMetadata\Shared\Grpc;

class Cart
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Á
shared/grpc/cart.protocart"5
GetCartRequest
user_id (

session_id (	"<
CartResponse
items (2.cart.CartItem
total ("`
CartItem

product_id (
title_snapshot (	
price_snapshot (
quantity (2B
CartService3
GetCart.cart.GetCartRequest.cart.CartResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

