<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/grpc/cart.proto

namespace App\Grpc\GPBMetadata;

class Cart
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
ö
shared/grpc/cart.protocart"5
GetCartRequest
user_id (

session_id (	"H
CartResponse

id (	
total (
items (2.cart.CartItem"`
CartItem

product_id (
title_snapshot (	
price_snapshot (
quantity (2B
CartService3
GetCart.cart.GetCartRequest.cart.CartResponseB\'ÊApp\\Grpc\\CartâApp\\Grpc\\GPBMetadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

