<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/grpc/cart.proto

namespace App\Grpc\Cart;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cart.CartItem</code>
 */
class CartItem extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 product_id = 1;</code>
     */
    protected $product_id = 0;
    /**
     * Generated from protobuf field <code>string title_snapshot = 2;</code>
     */
    protected $title_snapshot = '';
    /**
     * Generated from protobuf field <code>double price_snapshot = 3;</code>
     */
    protected $price_snapshot = 0.0;
    /**
     * Generated from protobuf field <code>int32 quantity = 4;</code>
     */
    protected $quantity = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $product_id
     *     @type string $title_snapshot
     *     @type float $price_snapshot
     *     @type int $quantity
     * }
     */
    public function __construct($data = NULL) {
        \App\Grpc\GPBMetadata\Cart::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 product_id = 1;</code>
     * @return int|string
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Generated from protobuf field <code>int64 product_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProductId($var)
    {
        GPBUtil::checkInt64($var);
        $this->product_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string title_snapshot = 2;</code>
     * @return string
     */
    public function getTitleSnapshot()
    {
        return $this->title_snapshot;
    }

    /**
     * Generated from protobuf field <code>string title_snapshot = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitleSnapshot($var)
    {
        GPBUtil::checkString($var, True);
        $this->title_snapshot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double price_snapshot = 3;</code>
     * @return float
     */
    public function getPriceSnapshot()
    {
        return $this->price_snapshot;
    }

    /**
     * Generated from protobuf field <code>double price_snapshot = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPriceSnapshot($var)
    {
        GPBUtil::checkDouble($var);
        $this->price_snapshot = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 4;</code>
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Generated from protobuf field <code>int32 quantity = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt32($var);
        $this->quantity = $var;

        return $this;
    }

}

